# Generated by Django 4.2 on 2023-04-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_mycomicslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycomicslist',
            name='progress',
            field=models.CharField(default='reading', max_length=255),
        ),
    ]
