# Generated by Django 4.2 on 2023-04-15 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mycomicslist_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comics', to='api.type'),
        ),
        migrations.AlterField(
            model_name='mycomicslist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_list', to='api.user'),
        ),
    ]
