# Generated by Django 4.2 on 2023-04-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_comics_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comics',
            name='published',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='comics',
            name='pic',
            field=models.CharField(max_length=255),
        ),
    ]
