# Generated by Django 4.2 on 2023-04-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.AlterField(
            model_name='comics',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='comics',
            name='genre',
        ),
        migrations.AlterField(
            model_name='comics',
            name='pic',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=75),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='comics',
            name='genre',
            field=models.ManyToManyField(null=True, related_name='comics', to='api.genre'),
        ),
    ]
