# Generated by Django 4.2 on 2023-04-16 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_comics_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
    ]
