# Generated by Django 4.2 on 2023-04-16 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_genre_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycomicslist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_list', to='api.user'),
        ),
    ]
