# Generated by Django 4.2 on 2023-04-22 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_mycomicslist_mycomics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('comics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.comics')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='api.user')),
            ],
        ),
    ]
