# Generated by Django 4.2 on 2023-05-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_comments_comics_discussion_comments_discussion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['created_time']},
        ),
    ]
