# Generated by Django 4.2 on 2023-05-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_news_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='pic',
            field=models.URLField(null=True),
        ),
    ]
